# Generated by Django 5.0.1 on 2024-03-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100)),
                ('Imagen', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
