# Generated by Django 5.0.1 on 2024-03-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_customuser_options_remove_customuser_apellidos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
