# Generated by Django 5.0.1 on 2024-03-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.destino')),
            ],
            options={
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
