# Generated by Django 5.0.1 on 2024-03-08 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0010_alter_reservacion_fecha_alter_reservacion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 4, 23, 48, 383962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2024, 3, 8, 4, 23, 48, 383962, tzinfo=datetime.timezone.utc)),
        ),
    ]
